// One-off: downloads the latin subset of each Google Font into ./fonts and writes css/fonts.css.
// Run with: node scripts/fetch-fonts.mjs
import { mkdir, writeFile } from 'node:fs/promises';

const UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0 Safari/537.36';

const FAMILIES = [
  { family: 'Jost',            query: 'Jost:wght@300..700',                file: 'jost' },
  { family: 'Caveat',            query: 'Caveat:wght@400..700',              file: 'caveat' },
  { family: 'Permanent Marker',  query: 'Permanent+Marker',                  file: 'permanent-marker' },
  { family: 'Special Elite',     query: 'Special+Elite',                     file: 'special-elite' },
  { family: 'Reenie Beanie',     query: 'Reenie+Beanie',                     file: 'reenie-beanie' },
];

await mkdir('fonts', { recursive: true });
let css = '/* Generated by scripts/fetch-fonts.mjs — latin subsets, self-hosted. */\n';

for (const f of FAMILIES) {
  const res = await fetch(`https://fonts.googleapis.com/css2?family=${f.query}&display=swap`, { headers: { 'User-Agent': UA } });
  const text = await res.text();
  const blocks = text.split('/* ').slice(1).map(b => '/* ' + b);
  const latin = blocks.find(b => b.startsWith('/* latin */'));
  if (!latin) throw new Error(`No latin block for ${f.family}`);
  const url = /url\((https:[^)]+\.woff2)\)/.exec(latin)[1];
  const buf = Buffer.from(await (await fetch(url)).arrayBuffer());
  const out = `fonts/${f.file}.woff2`;
  await writeFile(out, buf);
  const weight = /font-weight:\s*([^;]+);/.exec(latin)[1];
  const range = /unicode-range:\s*([^;]+);/.exec(latin)[1];
  css += `@font-face {\n  font-family: '${f.family}';\n  font-style: normal;\n  font-weight: ${weight};\n  font-display: swap;\n  src: url('../${out}') format('woff2');\n  unicode-range: ${range};\n}\n`;
  console.log(`${f.family}: ${(buf.length / 1024).toFixed(1)} KB (${weight})`);
}
await writeFile('css/fonts.css', css);
